### ISSUE TITLE
Export Birthday date

### ISSUE THREAD

**Issue by olibrian** [puzzle/skills#200]
When exporting the CV, the date of birth is exported incorrectly to the odt file. Does not apply to all CVs. Example: https://cv.puzzle.ch/people/1326 

Current date of birth in cv.puzzle.ch: 09.11.1985
Export date of birth in otd File: 08.11.1985

The goal would be to have the same date in the tool as in the export.

**Comment by Robin481** [comment]
This is due to a time zone problem with our datepicker. The Dates were set -1h due to our local timezone hence the (e.g.) 26.08.1995 00:00 turned into the 25.08.1995 23:00. Our Frontend in turn adapted this again in the other direction and displayed it correctly +1h as 26.08.1995: 00:00
https://github.com/adopted-ember-addons/ember-pikaday
We can probably solve this by setting the useUTC flag.
