### ISSUE TITLE
Sorting of skills when adding a new one

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#337]
When adding a new Skill under: Profile -> Skills -> new-Skills, the suggested skills are sorted by Uppercase and Lowercase, meaning all lowercase skills will appear at the end of the list ignoring the alphabetical order.

Definiton of done:
- The Skills are only sorted by alphabetical order (not upper- lowercase)
- There is a fitting test written for this functionality.

**Comment by dovaya** [comment]
The reason why the sort function *orderByTitleCaseInsensitive* in the *skills/frontend/app/components/people-skill-new.js* file tests if the skill titles are undefined is because whenever the modal to add a new People-Skill is opened and closed/aborted without actually adding a new People-Skill, both an empty skill and an empty People-Skill are created (->empty records with every property set to *undefined*). This bug was present before I changed any code. -> needs more investigation
