### ISSUE TITLE
Skill-Search AND

### ISSUE THREAD

**Issue by Robin481** [puzzle/skills#342]
In the Skill-Search only searching for one field has limited uses. Adding more than one Skill to the search would make combined searches possible and therefore increase its usability manyfold. 

A User should be able to add (up to a maximum of 5, just to avoid design issues) Skills to search for. Each of these Skills can have the minimum expierience filter as well (as added in https://github.com/puzzle/skills/issues/336).
For now this search is an AND search, meaning when a User for example adds "Rails", "EmberJS" and "Bootstrap" the search will only yield users with all these 3 Skills in their profile.
Furthermore a User could add the miminum experience of "Senior" to "Rails" and therefore only get Users that have the afore mentioned "Skills" plus a seniority level of "Senior" in Rails. 

Definition of Done:
- A user can add up to 5 skills to search for in the Skill-Search.
- This search is an AND search and will search for profiles with all the selected Skills. 
- The minimum experience selector also has to work. Making combined searches possible.
- The added search fields can be removed via a close button next to them (not in the mockup)
- When closing and reopening a Skill-Field it should not be prepopulated 
- Extensive tests are added for this feature.

**Comment by Robin481** [comment]
Crude mockup:
![AND-search](https://user-images.githubusercontent.com/32168247/77317923-68974280-6d0c-11ea-8e4b-603228057dcc.png)

**Comment by dovaya** [comment]
After having a look at the code yesterday, I can't help but feel that we have to change the query to the backend and the model that ember uses in the frontend.

Up until now, the search function was looking for people_skills themselves - which was fine, since you could only search for one skill and an linked level.

Now, with the possibility to search for multiple skills and levels, we are not looking for the people_skills themselves, but for the people who do have said desired skills.
(The skills that we want are already defined by the filters (dropdowns and ui-sliders), what we are looking for now are the people who do have said desired skills.)

We will have to implement a query akin to:

```
SELECT people.person_id FROM people LEFT JOIN people_skills ON people.person_id = people_skills.person_id
WHERE ((people_skills.skill_id = [skill_id first skill] AND people_skills.level = [level first skill] ) OR (people_skills.skill_id = [skill_id second skill] AND people_skills.level = [level second skill]) OR ...[further where clauses for further skills]) GROUP BY people.person_id HAVING COUNT(people.person_id) > [amount of defined skills in the where clauses]
```

This gives us the person_id's of the people who have all desired skills, and we can hook them in the person model and put them in the results table with links to their profile pages.

(Maybe we can also reuse some code or business logic from the cv-search, since that search itself searches for people, I think..)
