### ISSUE TITLE
(3) Email Regex is missing in Person new and Person edit

### ISSUE THREAD

**Issue by njaeggi** [puzzle/skills#497]
Currently it's possible to put any text in the email field when creating or editing a person, add a simple email regex to prevent this from happening

**Comment by lkleisa** [comment]
Draft PR: https://github.com/puzzle/skills/pull/501

**Comment by lkleisa** [comment]
I added email regex in validation file `frontend/app/validations/person-form.js`. We have the following problems: 
1)  We need to pass in some way the translated version of the message `Gib eine gültige Email Adresse ein`. It should be possible to pass a [custom validation message](https://github.com/poteto/ember-changeset-validations#custom-validation-messages), but I could not make it. 
2) The form validation of the person new is somewhere in backend and not like the person edit in frontend. Because of that, we can not use the same validation file `frontend/app/validations/person-form.js`. It would make sense to move the backend validation to the frontend (if we have the time for that). But if not, we have to add an email validation in backend

Good doc: https://github.com/poteto/ember-changeset-validations

**Comment by lkleisa** [comment]
Todo: 
- [ ] Use translation for error message
- [ ] Define, if we use backend or frontend or both for validations
- [ ] Fix bug with second click on submit button
- [ ]  Write tests
- [ ] Smoke test

**Comment by lkleisa** [comment]
Frontend test for edit person is done, now 2 for create person is needed....

**Comment by lkleisa** [comment]
The problem with the frontend test is the following: 
In person new, the whole person object is sent to the backend. There happens the validation. The rails return the error and in ember, we display it with an alert. In person edit, the validation happens in frontend. We can easily test, if there is a validation error or not. In person new, it's a little bit more difficult. 
When we use a debugger and the developer mode in the test, we see when we click on the submit button, that for some ms the alerts are displayed. Also, when we use a debugger before the error rendering, we have the 2 errors from the backend in right form (1: email muss ausgefüllt sein, 2: email format nicht gültig). 
@mtnstar will look about it tomorrow
