### ISSUE TITLE
Bilder mit Umlauten im Namen können nicht korrekt hochgeladen werden

### ISSUE THREAD

**Issue by RandomTannenbaum** [puzzle/skills#675]
Wenn man als Benutzer im Profil ein Bild mit einem Umlaut im Namen hochlädt, so wird zwar anscheinend das alte Bild entfernt, aber das neue Bild kann vom Server nicht gefunden werden und man bekommt einen error-code 500 vom Server.

**Comment by ManuelMoeri** [comment]
### Findings so far:
*Response to upload request*
This response occurs when uploading a file named "OKR-Tööl". The error code is 500 or "Internal Server Error".
![image](https://github.com/puzzle/skills/assets/109959820/d152965a-94e5-4a42-b715-8a14a7e6790e)

*The Picture in the uploads folder on VS-Code*
The picture is saved to a person named "Sandor Clegane" with the ID "16". That's why it's in the /uploads/person/picture/16 folder.
![image](https://github.com/puzzle/skills/assets/109959820/d36240dc-6222-491d-bb5b-aa77d7e614f1)
